before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: L85kWI865SjJkJDn+UxTFqRvqNDOlQ21tof9EtSVEhe1TAhsfm3V0w8wUhdKXjMNoDlIDuvzZ2Tiae/i+qYhTw1E1jUAtHTICeBH1crjykGw2v1aW+hu03zFdXJoJL3xVTupr0pyy0p6iy/ASXtfsvdZ1vkGuHqC0q7Fd3uUx6AQSEupQiKSXEwYk0Dx96V2eEdfyu+NmbVlS6DqBQqMvpI+/uG1aJLUgt8z3/J0qqvtvo1+1IAZ7F3RBBxHhI8TDkcdxwXyegpt4MXz55WAwgYX9yG+uYgsF6q0VUM3PTGf/Xd1/79MdgrUOVky8Dd7fmfucoi+5Go4UACW/gmz3gUEpqpgltaP49f5JAeIr3rv8iuiQqOG821ul53b9xEPuYWq1JfpRsZRnRogeo5yhxNqN+eQOk6mCYf2uhg5i0LcwVL1tNSze/R8MeKm3rUGQr37jtPdRTWr4OrNLdUfyruUGc537ah/8TRYhrxLB6oX5zUeh4hwrXRGbBp5GjnQMeUHaZ7o6MHSpGDoDJ++zKvDrpXiJ4e2WqW2zFytccfSrNo2891y2Jqkkn5XcuIWtX/sqOu+VxVXKk5of4b+7EBY5T/Xixb7EshYZzui4gS0DLmqrwvtrjEvBE0ZU4KR5riSk3FUSuzW8rgzVUyrZupgvq1gB/Durpf0eDxZo3M= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
